name: Build and Test Portfolio

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Prerequisites
      run: |
        make install-gtest
        make install-format

    - name: Lint
      run: make check-format

    - name: Build Debug
      run: BUILD_TYPE=Debug make clean build

    - name: Test
      working-directory: build
      run: make Test

    - name: Build Release
      run: make clean build
  
    - name: Test
      working-directory: build
      run: make Test

    - name: Python
      run: |
        make install-python
        make run-python
