name: Build and Test Portfolio

on:
  push:
    branches: [ "*" ]
#  pull_request:
#    branches: [ "master" ]

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: registry-1.docker.io/v1
  BUILDX_VERSION: latest
  BUILDKIT_IMAGE: moby/buildkit:buildx-stable-1
  LATEST_TAG: djferen/portfolio:latest
  TEST_TAG: djferen/portfolio:test  

jobs:
  # 
  docker:
    runs-on: ubuntu-latest
    environment: new-env    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64 # ,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}
      - name: Run docker based build
        run: make run-env docker-build

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Prerequisites
      run: |
        make install-prerequisites

    - name: Lint
      run: make check-format

    - name: Build Env
      run: make build-env run-env

    - name: Build Debug
      run: BUILD_TYPE=Debug make clean build

    - name: Test Debug
      working-directory: build
      run: make Test

    - name: Build Release
      run: make clean build
  
    - name: Test Release
      working-directory: build
      run: make Test

    - name: Python
      run: |
        make install-python
        make run-python

    - name: Rust
      run: |
        make install-rust
        make build-rust
        make test-rust
