name: Build and Test Portfolio

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Prerequisites
      run: |
        make install-prerequisites

    - name: Lint
      run: make check-format

    - name: Build Env
      run: make build-env

    - name: Build Debug
      run: BUILD_TYPE=Debug make clean build

    - name: Test Debug
      working-directory: build
      run: make Test

    - name: Build Release
      run: make clean build
  
    - name: Test Release
      working-directory: build
      run: make Test

    - name: Python
      run: |
        make install-python
        make run-python

    - name: Rust
      run: |
        make install-rust
        make build-rust
        make test-rust
